# ===================================
# CONFIGURAÇÃO PADRÃO
# ===================================
server:
  port: 8081
  error:
    include-message: always

spring:
  profiles:
    active: prod # Força o perfil de produção no servidor

  thymeleaf:
    cache: true # Em produção o cache ajuda na performance

  jpa:
    hibernate:
      ddl-auto: update # Cria as tabelas no Postgres automaticamente
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# ===================================
# PERFIL PRODUÇÃO (PARA A VPS)
# ===================================
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_zenlog_db
    username: portfolio_lucasalmeida
    password: Lucas2002--

  # Desativando RabbitMQ para não dar erro no boot
  rabbitmq:
    listener:
      type: simple
      direct:
        enabled: false

  # Se você não for usar a IA agora, pode deixar em branco
  # ou remover o Service que a chama no código Java.
  ai:
    openai:
      enabled: false

api:
  security:
    token:
      secret: ${SECRET_SPRING_SECURITY:uma_senha_padrao_para_nao_dar_erro}

      spring:
        autoconfigure:
          exclude:
            - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
            - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
            - org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration